### ISSUE TITLE
Je gebruikt nog style elementen in je css die ook in de gedeelde stylesheet staan (Code review)

### ISSUE THREAD

**Issue by Patrickkhr** [RickFDND/fix-the-flow-interactive-website#1]
Je eigen stylesheet gebruikt nog style elementen op het a element, die ook al in de gedeelde stylesheet staan "text-decoration" en "border-radius" deze kun je weghalen.

https://github.com/RickFDND/look-and-feel-corporate-identity/blob/ec212fa5b12de8d4bb57b07dd03bde10c5da02da/style.css#L36-L47

**Comment by RickFDND** [comment]
gefixt
