### ISSUE TITLE
Je styling op de headings is te algemeen

### ISSUE THREAD

**Issue by Patrickkhr** [RickFDND/fix-the-flow-interactive-website#2]
Probeer in plaats van algemene selectors zoals h1,h2,h3 een class selector te gebruiken, bijvoorbeeld H1 = .text-xxl H2 = .text-xl H3 = .text-l etc. Hiermee zorg je ervoor dat je in de html de juiste headings kan selecteren en kun je door gebruik te maken van de classes de styling bepalen.

https://github.com/RickFDND/look-and-feel-styleguide/blob/f6576dfd6ad810cf73c5c41858dde654822169da/Drop%26Heal.css#L66-L85

**Comment by RickFDND** [comment]
gefixt
