### ISSUE TITLE
Probeer transities/animaties in je ontwerp te verwerken

### ISSUE THREAD

**Issue by KrijnHoetmer** [RickFDND/fix-the-flow-interactive-website#5]

**Comment by RickFDND** [comment]
gefixt op pagina 3 met hover over de images

**Comment by KrijnHoetmer** [comment]
Probeer de volgende keer je commit aan dit issue te koppelen, door het issue nummer te noemen in je commit message (#5 in dit geval). Het is nu niet duidelijk wat je gedaan hebt, dus als issue-inschieter kan ik ook niet beoordelen of het is wat ik bedoelde. Heb je een link naar je commit of stukje code?

**Comment by RickFDND** [comment]
Ik begrijp hoe dit werkt maar ik had al de issue opgelost en gepushed vanwege de sprintreview

**Comment by KrijnHoetmer** [comment]
Begrijpen en doen zijn twee verschillende dingen :) Probeer dit dus ook te _doen_.
